CREATE TABLE "user" (
   ID SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   date_create VARCHAR(255) NOT NULL,
   is_admin BOOLEAN NOT NULL DEFAULT FALSE,
   is_active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE movie (
   ID SERIAL PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   description VARCHAR(255),
   year INTEGER,
   fk_genre BIGINT,
   fk_director BIGINT
);

CREATE TABLE genre (
   ID SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL
);

CREATE TABLE director (
   ID SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255)
);

CREATE TABLE actor (
   ID SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255)
);

CREATE TABLE movie_has_actor (
   ID SERIAL PRIMARY KEY,
   fk_movie BIGINT,
   fk_actor BIGINT
);

CREATE TABLE classification (
   ID SERIAL PRIMARY KEY,
   fk_user BIGINT,
   fk_movie BIGINT,
   classification INTEGER NOT NULL
);


ALTER TABLE movie ADD CONSTRAINT FK_951f0651_6fa7_4732_8ae8_3a488ba89878 FOREIGN KEY (fk_genre) REFERENCES genre(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE movie ADD CONSTRAINT FK_668693b0_b844_4d01_87c4_c3560298b2c5 FOREIGN KEY (fk_director) REFERENCES director(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE movie_has_actor ADD CONSTRAINT FK_8e8b0a31_1ad5_4200_905c_f07dbe80eab7 FOREIGN KEY (fk_movie) REFERENCES movie(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE movie_has_actor ADD CONSTRAINT FK_45b00436_8793_48a7_beec_e7a51d14d517 FOREIGN KEY (fk_actor) REFERENCES actor(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE classification ADD CONSTRAINT FK_fcf2da90_ddc6_4ccf_a0a8_f22af2b6f487 FOREIGN KEY (fk_user) REFERENCES "user"(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE classification ADD CONSTRAINT FK_5122ee12_8e54_4f35_9752_0c31421f38e5 FOREIGN KEY (fk_movie) REFERENCES movie(ID) ON DELETE CASCADE ON UPDATE CASCADE;

